#!/bin/bash

#Identify and display the Ethernet interface characteristics:
# (a) Identify broadcast address
# (b) Identify all IP adresses which are part of the same subnet


ifconfig en0 | grep broadcast |cut -d ' ' -f 6
echo 
arp -a | cut -d ' ' -f 2 | tr -d '()'
